basePath: /
host: localhost:8000
info:
  contact:
    name: Guilherme Chaves
  description: This is a sample server.
  license:
    name: Full Cycle license
    url: http://www.fullcycle.com.br
  termsOfService: http://swagger.io/terms/
  title: Go Expert API Example
  version: "1.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
